### ISSUE TITLE
Add as local component

### ISSUE THREAD

**Issue by Turqueso** [Orlandster/vue-typed-js#4]
Can this be added as a local component?

**Comment by Orlandster** [comment]
@Turqueso Yeah, sure. You can basically just import it into your component and register it via components prop:

```
`import VueTypedJs from 'vue-typed-js'`

new Vue({ 
 el: '#app',
 components: { 'vue-typed': VueTypedJs  }
})
```


Something like this should work.

**Comment by DeniseWalter** [comment]
Hey, so I'm on Vue CLI 3, and found in order to add it as a local component, I actually had to import it like this: 

```import VueTypedJs from 'vue-typed-js/src/components/VueTypedJs.vue'```

Otherwise, if I was importing it in the standard way: 

`import VueTypedJs from 'vue-typed-js'`, I'd get the following error message: 
```[Vue warn]: Failed to mount component: template or render function not defined.```

Not sure if this coming from the way my project is set up, but wanted to put it out there in case anyone else is running into the same issue.

**Comment by codingsett** [comment]
@DeniseWalter Thanks...i had the same issue

**Comment by intositeme** [comment]
Same issue here

**Comment by markojak** [comment]
Also had this issue - Is this package even maintained anymore?

**Comment by roozbeheslami** [comment]
You should import it into your component like this:
var VueTypedJs = require("vue-typed-js").VueTypedJs;
